Repository CERTCC/SSVC, pull requests merged in 2023-07, with the labels that each got.

#264 Replace κ with *k* to avoid pandoc font errors in build process
  doc/md_src_files/10_evaluation_of_draft_trees.md
  doc/md_src_files/13_future_work.md
  doc/ssvc.html
  doc/ssvc.pdf
Labels: bug

#258 Change default tree to Deployer.json
  ssvc-calc/ssvc.js
Labels: enhancement, ssvc-calc

#267 Make Public Safety Impact values consistent throughout
  data/csvs/coord-triage-options.csv
  doc/graphics/ssvc_2_coord-triage.tex
  src/enumerate-coord-triage-options.sh
  ssvc-calc/Coordinator-Triage.json
Labels: bug, documentation

#270 Update analyze_csv.py to reflect csv column name changes
  src/analyze_csv.py
Labels: bug

#271 EPSS changes
  doc/md_src_files/05_01_exploitation.md
  doc/md_src_files/12_related_systems.md
  doc/md_src_files/sources_ssvc.bib
Labels: documentation

#276 Adjust Supplier Tree decisions
  data/csvs/supplier-options.csv
  doc/graphics/ssvc_2_deployer_SeEUMss.pdf
  doc/graphics/ssvc_2_deployer_SeEUMss.tex
  doc/graphics/ssvc_2_supplier.pdf
  doc/graphics/ssvc_2_supplier.tex
  src/SSVC_csv-to-latex.py
  ssvc-calc/Deployer.json
  ssvc-calc/Supplier.json
Labels: enhancement

#279 Update style guide and acks
  doc/README.md
  doc/crossref-how-to.md
  doc/md_src_files/16_acknowledgements.md
  doc/reference-how-to.md
  doc/style-guide-how-to
Labels: documentation

#269 Update Changelog for v2.1
  doc/md_src_files/09_changelog.md
  doc/md_src_files/17_contact_us.md
Labels: documentation

#283 update pdf and html drafts
  draft/ssvc.html
  draft/ssvc.pdf
Labels: documentation

#286 fix typos in json schema descriptions
  data/schema/SSVC_Computed.schema.json
  data/schema/SSVC_Provision.schema.json
Labels: bug, documentation
