Repository CERTCC/SSVC, pull requests merged in 2023-06, with the labels that each got.

#250 Update 055_decision-points_2.md
  doc/md_src_files/055_decision-points_2.md
Labels: documentation, enhancement

#256 add subsubsection header for tree versioning
  doc/md_src_files/060_decision-trees.md
Labels: documentation

#262 Adjust deployer tree decisions
  data/csvs/deployer-options.csv
  data/csvs/deployer-options_v2_1.csv
Labels: enhancement

#263 Rename markdown files to match current chapter and section names
  doc/Makefile
  doc/md_src_files/01_introduction.md
  doc/md_src_files/02_state_of_practice.md
  doc/md_src_files/03_representing_information.md
  doc/md_src_files/040_stakeholders-scope.md
  doc/md_src_files/04_00_vulnerability_management_decisions.md
  doc/md_src_files/04_01_enumerating_stakeholders.md
  doc/md_src_files/04_02_enumerating_decisions.md
  doc/md_src_files/04_03_enumerating_actions.md
  doc/md_src_files/04_04_items_with_same_priority.md
  doc/md_src_files/04_05_risk_tolerance_and_priority.md
  doc/md_src_files/04_06_scope.md
  doc/md_src_files/050_decision-points_1.md
  doc/md_src_files/05_00_likely_decision_points.md
  doc/md_src_files/05_01_exploitation.md
  doc/md_src_files/05_02_technical_impact.md
  doc/md_src_files/05_03_automatable.md
  doc/md_src_files/05_04_value_density.md
  doc/md_src_files/05_05_utility.md
  doc/md_src_files/05_06_safety_impact.md
  doc/md_src_files/05_07_mission_impact.md
  doc/md_src_files/05_08_human_impact.md
  doc/md_src_files/05_09_system_exposure.md
  doc/md_src_files/060_decision-trees.md
  doc/md_src_files/06_00_coordination_decisions.md
  doc/md_src_files/06_04_publication_decision.md
  doc/md_src_files/07_00_prioritization.md
  doc/md_src_files/07_01_supplier_tree.md
  doc/md_src_files/07_02_deployer_tree.md
  doc/md_src_files/07_03_coordinator_trees.md
  doc/md_src_files/07_04_tree_customization.md
  doc/md_src_files/07_05_evidence_gathering.md
  doc/md_src_files/07_06_asset_management.md
  doc/md_src_files/07_07_development_methodology.md
  doc/md_src_files/08_communicating_results.md
  doc/md_src_files/09_changelog.md
  doc/md_src_files/10_evaluation_of_draft_trees.md
  doc/md_src_files/11_worked_example.md
  doc/md_src_files/12_related_systems.md
  doc/md_src_files/13_future_work.md
  doc/md_src_files/14_limitations.md
  doc/md_src_files/15_conclusion.md
  doc/md_src_files/16_acknowledgements.md
  doc/md_src_files/17_contact_us.md
  doc/md_src_files/18_copyright.md
  doc/md_src_files/19_reference_definitions.md
  doc/ssvc.html
  doc/ssvc.pdf
Labels: documentation, enhancement
