Repository CERTCC/SSVC, pull requests merged in 2024-04, with the labels that each got.

#553 Add link to certcc.github.io home page
  mkdocs.yml
Labels: enhancement, environment

#549 Update changelog
  docs/about/changelog.md
Labels: bug, documentation

#559 Updated Mission-Impact in Deployer.json and in csvs/child_trees to ma…
  data/csvs/child_trees/human-impact.csv
  docs/ssvc-calc/Deployer.json
Labels: bug
