Repository CERTCC/SSVC, pull requests merged in 2024-02, with the labels that each got.

#423 Improve Reference section intro pages
  docs/reference/code/index.md
  docs/reference/decision_points/index.md
  docs/reference/decision_points/likely_decision_points.md
  docs/reference/index.md
  mkdocs.yml
Labels: documentation, enhancement

#425 Add OutcomeGroup for TheParanoids PrioritizedRiskRemediation
  src/ssvc/outcomes/groups.py
Labels: enhancement, python

#426 Add OutcomeGroup for CISA's customized version of SSVC
  src/ssvc/outcomes/groups.py
Labels: enhancement, python

#453 Move asset management to topics from howto
  docs/topics/asset_management.md
  mkdocs.yml
Labels: documentation

#446 merge report credibility description with its decision point page
  docs/reference/decision_points/report_credibility.md
  docs/topics/credibility_indicators.md
  docs/topics/index.md
  mkdocs.yml
Labels: documentation, enhancement

#452 Unlink text in changelog.md
  docs/about/changelog.md
Labels: documentation, enhancement

#440 ADRs for Decision Points and Outcomes as ordered sets
  docs/about/index.md
  docs/adr/0008-decision-points-are-ordered-sets.md
  docs/adr/0009-outcomes-are-ordered-sets.md
  docs/adr/_template.md
  docs/adr/index.md
  mkdocs.yml
Labels: documentation, environment

#444 ADR: Outcome sets are separate from decision point group (tree) identity
  docs/adr/0010-outcome-sets-are-separate-from-decision-point-groups.md
  docs/adr/index.md
Labels: documentation, environment

#457 Add mkdocs group to dependabot.yml
  .github/dependabot.yml
Labels: enhancement, environment

#451 Remove abbreviated format from docs
  docs/howto/communicating_results.md
  docs/topics/future_work.md
Labels: documentation, enhancement

#464 Bump site copyright
  mkdocs.yml
Labels: documentation, enhancement

#443 Fix broken links
  docs/adr/0005-ssvc-decision-point-group-versioning.md
  docs/howto/bootstrap/_steps_table.md
  docs/howto/bootstrap/collect.md
  docs/howto/bootstrap/index.md
  docs/howto/bootstrap/prepare.md
  docs/howto/bootstrap/summary.md
  docs/howto/bootstrap/use.md
  docs/howto/communicating_results.md
  docs/howto/coordination_decisions.md
  docs/howto/coordinator_publish_tree.md
  docs/howto/coordinator_trees.md
  docs/howto/evidence_gathering.md
  docs/howto/index.md
  docs/howto/prioritization.md
  docs/howto/publication_decision.md
  docs/howto/tree_customization.md
  docs/index.md
  docs/reference/decision_points/automatable.md
  docs/reference/decision_points/exploitation.md
  docs/reference/decision_points/human_impact.md
  docs/reference/decision_points/mission_impact.md
  docs/reference/decision_points/public_safety_impact.md
  docs/reference/decision_points/public_value_added.md
  docs/reference/decision_points/safety_impact.md
  docs/reference/decision_points/system_exposure.md
  docs/reference/decision_points/technical_impact.md
  docs/reference/decision_points/utility.md
  docs/reference/decision_points/value_density.md
  docs/reference/index.md
  docs/topics/asset_management.md
  docs/topics/decision_trees.md
  docs/topics/enumerating_actions.md
  docs/topics/evaluation_of_draft_trees.md
  docs/topics/formalization_options.md
  docs/topics/future_work.md
  docs/topics/index.md
  docs/topics/information_sources.md
  docs/topics/limitations.md
  docs/topics/related_systems.md
  docs/topics/representing_information.md
  docs/topics/state_of_practice.md
  docs/topics/units_of_work.md
  docs/topics/worked_example.md
  mkdocs.yml
Labels: bug, documentation

#465 Create link_checker.yml
  .github/workflows/link_checker.yml
Labels: enhancement, environment

#447 Add building block analogy explainer
  docs/topics/decision_points_as_bricks.md
  docs/topics/enumerating_decisions.md
  docs/topics/index.md
  mkdocs.yml
Labels: documentation, enhancement

#469 Revise `howto/index.md`
  docs/howto/index.md
Labels: bug, documentation, enhancement

#474 Expand SSVC acronym in site name
  mkdocs.yml
Labels: documentation

#468 Add community engagement links
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  CONTRIBUTING.md
  docs/_includes/helping_out.md
  docs/about/contact_us.md
  docs/about/contributing.md
  docs/about/index.md
  docs/index.md
  mkdocs.yml
Labels: documentation, enhancement, environment

#471 Make `link_checker.yml` run automatically on push to `main`
  .github/workflows/link_checker.yml
Labels: enhancement, environment

#476 Human impact change proposal
  docs/reference/decision_points/human_impact.md
Labels: documentation, enhancement

#479 make safety table formats look better
  data/json/decision_points/safety_impact_2_0_0.json
  docs/_generated/decision_points/safety_impact_2_0_0.md
  src/ssvc/decision_points/safety_impact.py
Labels: bug, documentation, enhancement

#473 Add topo sort to csv analyzer and policy generator
  data/json/decision_points/report_credibility_1_0_0.json
  data/json/decision_points/report_public_1_0_0.json
  docs/_generated/decision_points/report_credibility_1_0_0.md
  docs/_generated/decision_points/report_public_1_0_0.md
  src/ssvc/csv_analyzer.py
  src/ssvc/decision_points/report_credibility.py
  src/ssvc/decision_points/report_public.py
  src/ssvc/policy_generator.py
  src/test/test_csv_analyzer.py
  src/test/test_policy_generator.py
Labels: enhancement, python

#485 Consolidate stakeholder specific decision model content into individual howto pages
  data/json/decision_points/public_value_added_1_0_0.json
  docs/_generated/decision_points/public_value_added_1_0_0.md
  docs/_includes/_tree_notation_tip.md
  docs/howto/bootstrap/prepare.md
  docs/howto/coordination_decisions.md
  docs/howto/coordination_intro.md
  docs/howto/coordination_triage_decision.md
  docs/howto/deployer_tree.md
  docs/howto/publication_decision.md
  docs/howto/supplier_tree.md
  docs/howto/tree_customization.md
  docs/topics/enumerating_actions.md
  docs/topics/enumerating_decisions.md
  docs/topics/units_of_work.md
  mkdocs.yml
  src/ssvc/decision_points/public_value_added.py
Labels: documentation, enhancement, python

#488 Add _Establish Governance_ to _Prepare_ step of bootstrap process description
  docs/howto/bootstrap/_steps_table.md
  docs/howto/bootstrap/prepare.md
  docs/howto/bootstrap/summary.md
  docs/howto/bootstrap/use.md
Labels: bug, documentation, enhancement

#491 Add link to github tips wiki page
  docs/_includes/helping_out.md
Labels: documentation, enhancement

#490 Reorder HowTo and Understanding in site nav
  docs/howto/index.md
  docs/index.md
  docs/topics/index.md
  mkdocs.yml
Labels: documentation
