Repository CERTCC/SSVC, pull requests merged in 2024-03, with the labels that each got.

#517 Add Google Analytics
  mkdocs.yml
Labels: enhancement, environment

#520 SSVC calculator display updates for iframe
  docs/ssvc-calc/css.css
  docs/ssvc-calc/ssvc.js
Labels: user interface

#524 Copy edits & punch list
  docs/_includes/_cvss4_question.md
  docs/_includes/_scrollable_table.md
  docs/howto/bootstrap/collect.md
  docs/howto/bootstrap/use.md
  docs/howto/coordination_triage_decision.md
  docs/howto/deployer_tree.md
  docs/howto/index.md
  docs/reference/decision_points/exploitation.md
  docs/reference/decision_points/technical_impact.md
  docs/reference/decision_points/utility.md
  docs/topics/asset_management.md
  docs/topics/decision_points_as_bricks.md
  docs/topics/evaluation_of_draft_trees.md
  docs/topics/future_work.md
  docs/topics/information_sources.md
  docs/topics/items_with_same_priority.md
  docs/topics/related_systems.md
  docs/topics/worked_example.md
  docs/tutorials/index.md
Labels: bug, documentation, enhancement

#525 Update references in Risk Tolerance
  docs/topics/risk_tolerance_and_priority.md
Labels: documentation, enhancement

#526 Inline refs
  docs/topics/asset_management.md
  docs/topics/evaluation_of_draft_trees.md
  docs/topics/related_systems.md
  docs/topics/worked_example.md
Labels: documentation, enhancement

#518 Catch up README.md to current state
  README.md
  draft/ssvc.html
  pdfs/ssvc_2_1_draft.pdf
Labels: documentation, enhancement, environment

#507 Remove WIP disclaimer from home page
  docs/index.md
Labels: documentation

#532 Fix license link in CONTRIBUTING.md
  CONTRIBUTING.md
  LICENSE
Labels: bug, documentation, environment

#533 Set up site deployment on publish branch
  .github/workflows/deploy_site.yml
Labels: enhancement, environment

#535 Update enumerating_stakeholders.md
  docs/topics/enumerating_stakeholders.md
Labels: documentation, enhancement

#543 Configure sitemap.xml to be populated
  mkdocs.yml
Labels: enhancement, environment
