Repository CERTCC/SSVC, pull requests merged in 2025-08, with the labels that each got.

#867 SSVC Cacluator to accept new schema
  docs/ssvc-calc/ssvc.js
Labels: bug, enhancement

#885 Apply `black` and `markdownlint --fix`
  docs/adr/0012-ssvc-namespaces.md
  docs/reference/code/namespaces.md
  src/ssvc/_mixins.py
  src/ssvc/csv_analyzer.py
  src/ssvc/decision_points/cvss/helpers.py
  src/ssvc/decision_points/cvss/modified/modified_subsequent_availability_impact.py
  src/ssvc/decision_points/helpers.py
  src/ssvc/decision_points/ssvc/mission_impact.py
  src/ssvc/decision_tables/base.py
  src/ssvc/decision_tables/cisa/cisa_coordinate_dt.py
  src/ssvc/decision_tables/cvss/equivalence_set_five.py
  src/ssvc/decision_tables/cvss/equivalence_set_six.py
  src/ssvc/decision_tables/cvss/equivalence_set_two.py
  src/ssvc/decision_tables/helpers.py
  src/ssvc/decision_tables/ssvc/coord_pub_dt.py
  src/ssvc/decision_tables/ssvc/coord_triage.py
  src/ssvc/decision_tables/ssvc/deployer_dt.py
  src/ssvc/decision_tables/ssvc/human_impact.py
  src/ssvc/decision_tables/ssvc/supplier_dt.py
  src/ssvc/decision_tables/ssvc/utlity.py
  src/ssvc/doctools.py
  src/ssvc/dp_groups/cvss/collections.py
  src/ssvc/dp_groups/ssvc/collections.py
  src/ssvc/dp_groups/ssvc/coordinator_publication.py
  src/ssvc/dp_groups/ssvc/coordinator_triage.py
  src/ssvc/outcomes/basic/ike.py
  src/ssvc/outcomes/basic/value_complexity.py
  src/ssvc/outcomes/cvss/lmhc.py
  src/ssvc/outcomes/ssvc/coordinate.py
  src/ssvc/outcomes/ssvc/dsoi.py
  src/ssvc/outcomes/x_com_yahooinc/paranoids.py
  src/ssvc/policy_generator.py
  src/ssvc/registry/__init__.py
  src/ssvc/registry/base.py
  src/ssvc/registry/events.py
  src/ssvc/selection.py
  src/ssvc/utils/toposort.py
  src/test/decision_points/test_dp_base.py
  src/test/decision_tables/cvss/test_cvss_qsr4.py
  src/test/decision_tables/ssvc/test_coord_triage.py
  src/test/decision_tables/ssvc/test_human_impact.py
  src/test/decision_tables/test_base.py
  src/test/dp_groups/test_dp_groups.py
  src/test/registry/test_base.py
  src/test/test_doc_helpers.py
  src/test/test_doctools.py
  src/test/test_mixins.py
  src/test/test_namespaces_pattern.py
  src/test/test_policy_generator.py
  src/test/test_schema.py
  src/test/test_selections.py
  src/test/utils/__init__.py
  src/test/utils/test_toposort.py
Labels: python, tech/backend

#900 Add Documentation for DecisionTable objects
  data/json/decision_tables/ssvc/public_safety_impact_1_0_0.json
  data/json/ssvc_object_registry.json
  docs/reference/code/decision_point_groups.md
  docs/reference/code/decision_points.md
  docs/reference/code/decision_tables.md
  docs/reference/code/index.md
  docs/reference/decision_points/human_impact.md
  docs/reference/decision_points/public_safety_impact.md
  docs/reference/decision_points/utility.md
  mkdocs.yml
  src/ssvc/decision_tables/helpers.py
  src/ssvc/decision_tables/ssvc/public_safety_impact.py
  src/ssvc/decision_tables/ssvc/utility.py
  src/ssvc/dp_groups/cvss/collections.py
  src/ssvc/dp_groups/ssvc/collections.py
Labels: content/semantic, content/representation, tech/backend, tech/data

#914 Update CVE items to be unique and update tests see #905
  data/schema/v2/Decision_Point_Value_Selection-2-0-0.schema.json
  src/ssvc/selection.py
  src/test/test_selections.py
Labels: integration/blocker, integration

#906 change "policy" to "decision table" in relevant docs
  docs/howto/bootstrap/_steps_table.md
  docs/howto/bootstrap/prepare.md
  docs/howto/bootstrap/summary.md
  docs/howto/bootstrap/use.md
  docs/howto/coordination_triage_decision.md
  docs/howto/cvss_v4/eq1.md
  docs/howto/cvss_v4/eq2.md
  docs/howto/cvss_v4/eq3.md
  docs/howto/cvss_v4/eq4.md
  docs/howto/cvss_v4/eq5.md
  docs/howto/cvss_v4/eq6.md
  docs/howto/cvss_v4/qualitative.md
  docs/howto/deployer_tree.md
  docs/howto/publication_decision.md
  docs/howto/supplier_tree.md
  docs/reference/code/policy_generator.md
  docs/ssvc_overview.md
  docs/topics/decision_points_as_bricks.md
  docs/topics/enumerating_decisions.md
  docs/topics/enumerating_stakeholders.md
  docs/topics/index.md
  docs/tutorials/index.md
Labels: content/semantic

#917 Remove default volume mount in docker-compose config
  docker/docker-compose.yml
Labels: tech/backend

#919 Mark `ssvc.dp_groups.base` as deprecated
  data/schema/v2/Decision_Point_Group-2-0-0.schema.json
  docs/reference/code/decision_point_groups.md
  src/ssvc/dp_groups/base.py
Labels: tech/backend, tech/data
